# Generated by Django 3.0.7 on 2021-03-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use_Robot_inter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=50, verbose_name='用户id编号')),
                ('robot_id', models.CharField(max_length=50, verbose_name='机器人id编号')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intermediate_use_robot',
            },
        ),
    ]
