# Generated by Django 3.0.7 on 2021-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_use_robot_inter'),
    ]

    operations = [
        migrations.CreateModel(
            name='fa_piao_cha_yan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='upload/fa_piao_cha_yan')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fa_piao_cha_yan_table',
            },
        ),
    ]
