# Generated by Django 3.0.7 on 2021-03-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_fa_piao_cha_yan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_piao_cha_yan',
            name='down_file',
            field=models.FileField(default=1, upload_to='upload/fa_piao_cha_yan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fa_piao_cha_yan',
            name='file_stust',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
