# Generated by Django 3.0.7 on 2021-03-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_auto_20210330_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fa_piao_cha_yan',
            old_name='file_stust',
            new_name='file_state',
        ),
    ]
