# Generated by Django 3.0.7 on 2021-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_auto_20210330_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_piao_cha_yan',
            name='down_file',
            field=models.FileField(upload_to='upload/fa_piao_cha_yan/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fa_piao_cha_yan',
            name='file',
            field=models.FileField(upload_to='upload/fa_piao_cha_yan/%Y/%m/%d/'),
        ),
    ]
