# Generated by Django 3.0.7 on 2021-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_auto_20210330_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='fa_piao_shi_bie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='fa_piao_cha_yan/%Y/%m/%d/')),
                ('file_state', models.CharField(default=1, max_length=10)),
                ('down_file', models.FileField(upload_to='fa_piao_cha_yan/%Y/%m/%d/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fa_piao_cha_shi_bie',
            },
        ),
    ]
