# Generated by Django 3.0.7 on 2021-04-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0010_fa_piao_shi_bie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_piao_shi_bie',
            name='down_file',
            field=models.FileField(upload_to='fa_piao_shi_bie/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fa_piao_shi_bie',
            name='file',
            field=models.FileField(upload_to='fa_piao_shi_bie/%Y/%m/%d/'),
        ),
    ]
