# Generated by Django 3.0.7 on 2021-03-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32)),
                ('ment', models.CharField(max_length=30, verbose_name='部门')),
                ('use_id', models.CharField(max_length=18, unique=True, verbose_name='身份证')),
                ('unit_phone', models.CharField(max_length=18, verbose_name='办公电话')),
                ('chu_name', models.CharField(max_length=18, verbose_name='处室名称')),
                ('use_iphone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('use_address', models.CharField(max_length=32, verbose_name='办公地址')),
                ('use_unit', models.CharField(max_length=32, verbose_name='单位名称')),
                ('grade', models.CharField(max_length=32, unique=True, verbose_name='等级')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
    ]
