# Generated by Django 3.0.7 on 2021-03-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(max_length=32, verbose_name='等级'),
        ),
    ]
