# Generated by Django 3.0.7 on 2021-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210316_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.CharField(default=0, max_length=32, verbose_name='是否激活'),
        ),
    ]
